[package]
name = "ssh-connector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
exec = "0.3.1"
inquire = "0.6.2"
nix = "0.27.1"
thiserror = "1.0.51"
